### ISSUE TITLE
Uncaught TypeError: c.toUpperCase is not a function

### ISSUE THREAD

**Issue by A-kirami** [hyoban/unocss-preset-shadcn#2]
I encountered this error while trying to use shadcn-vue and unocss.

```
Uncaught TypeError: c.toUpperCase is not a function
    at chunk-U4IHFRBV.js:58:50
    at String.replace (<anonymous>)
    at chunk-U4IHFRBV.js:58:14
    at chunk-U4IHFRBV.js:53:33
    at setFullProps (chunk-U4IHFRBV.js:5584:49)
    at initProps (chunk-U4IHFRBV.js:5454:3)
    at setupComponent (chunk-U4IHFRBV.js:9019:3)
    at mountComponent (chunk-U4IHFRBV.js:7352:7)
    at processComponent (chunk-U4IHFRBV.js:7318:9)
    at patch (chunk-U4IHFRBV.js:6784:11)
```

The project where this issue occurred is inconvenient to troubleshoot, but I have reproduced this error through another method.
Just enable variant group transformer for unocss, and the same error will appear.

```ts
// unocss.config.ts
import {
  defineConfig,
  presetUno,
  transformerVariantGroup,
} from 'unocss'
import presetAnimations from "unocss-preset-animations"
import { presetShadcn } from "unocss-preset-shadcn"

export default defineConfig({
  presets: [presetUno(), presetAnimations(), presetShadcn()],
  transformers: [transformerVariantGroup()],
  content: {
    pipeline: {
      include: [
        /\.(vue|svelte|[jt]s|[jt]sx|mdx?|astro|elm|php|phtml|html)($|\?)/,
      ],
    },
  },
})
```

**Comment by hyoban** [comment]
It looks like `transformerVariantGroup` can not be used with `ts` file. It works fine if you remove `content.pipeline.include`. So this is not a bug with preset.

**Comment by hyoban** [comment]
Sorry for my mistake, we should not extracted all js/ts file.

https://unocss.dev/guide/extracting#extracting-from-build-tools-pipeline

```ts
// uno.config.ts
export default defineConfig({
  content: {
    pipeline: {
      include: [
        // the default
        /\.(vue|svelte|[jt]sx|mdx?|astro|elm|php|phtml|html)($|\?)/,
        // include js/ts files
        'src/**/*.{js,ts}',
      ],
      // exclude files
      // exclude: []
    },
  },
})
```

Will update doc soon.
